# Generated by Django 4.2.7 on 2026-06-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='verification_type',
            field=models.CharField(choices=[('face_bvn', 'Face + BVN')], max_length=50),
        ),
    ]
