# Generated by Django 4.2.7 on 2026-06-30 10:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_verification_verification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount spent by this client', max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, help_text='External reference ID (e.g., Stripe payment intent ID, PayPal transaction ID)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_method'], name='wallet_tran_payment_69bca8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_id'], name='wallet_tran_referen_1f3089_idx'),
        ),
    ]
